### ISSUE TITLE
Error: Cannot find module './config/bundleIdentifiers'

### ISSUE THREAD

**Issue by vuongtuananh** [junedomingo/react-native-rename#80]
After I install react-native-rename on my macbook, then run react-native-rename "MyNewName" -b abc.xyz.afg
It show error:
module.js:550
    throw err;
    ^

```
Error: Cannot find module './config/bundleIdentifiers'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-rename/lib/index.js:45:26)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by vuongtuananh** [comment]
I found out that lack file bundleIdentifiers.js in usr⁩ ▸ ⁨local⁩ ▸ ⁨lib⁩ ▸ ⁨node_modules⁩ ▸ ⁨react-native-rename⁩ ▸ ⁨lib⁩ ▸ ⁨config⁩. 
So i copy that file from node_modules to there. It worked!
